--- 
pid: tmp/pids/thin.pid
wait: 30
timeout: 30
log: log/thin.log
max_conns: 20000
require: []

max_persistent_conns: 512
environment: production
servers: 4
port: 5000
daemonize: true
chdir: /webapps/escolinhas
address: 0.0.0.0
threaded: true
